image: registry.gitlab.com/skygard/send:latest

services:
  - mysql:5.7

# Cache vendor and node_modules between builds
cache:
  paths:
    - vendor/
    - node_modules/
    
test:
  stage: test

  before_script:
    - composer install
    - npm install

  script:
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
    - npm run test